REQUEST_STATUS_NORMAL = "NORMAL"
REQUEST_STATUS_ATTACK = "ATTACK"
REQUEST_STATUS_SUSPICIOUS = "SUSPICIOUS"

ATTACK_HTTP_FLOOD = "HTTP_FLOOD"
ATTACK_SYN_FLOOD = "SYN_FLOOD"
ATTACK_UDP_FLOOD = "UDP_FLOOD"

DETECTION_RULE_ENGINE = "RULE_ENGINE"
DETECTION_ML = "ISOLATION_FOREST"
DETECTION_HYBRID = "HYBRID"